
before_install:
  - apt-get install vagrant
  - cp vagrant/Vagrantfile .

install:
  - vagrant up
  - vagrant ssh
  - curl -sSL https://get.docker.io/ubuntu/ | sudo sh
  
#script:
#  - sudo docker -d 
#  - sudo docker run ubuntu echo "hello world" 
